spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://users-svc
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://users-svc
          predicates:
            - Path=/api/v1/auth/**
        - id: catalog-service
          uri: lb://catalog-svc
          predicates:
            - Path=/api/v1/catalog/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-svc.default.svc.cluster.local:8761/eureka/
