spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://35.237.124.228
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: http://35.237.124.228
          predicates:
            - Path=/api/v1/auth/**
        - id: catalog-service
          uri: lb://catalog-svc
          predicates:
            - Path=/api/v1/catalog/**
eureka:
  client:
    service-url:
      defaultZone: http://34.138.194.76:8761/eureka/

