spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtTokenFilterFactory
  profiles:
    active: debug
server:
  port: 8080