spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Hace que los nombres de las rutas sean en minúsculas
eureka:
  client:
    service-url:
      defaultZone: http://34.138.194.76:8761/eureka/
